# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-03-25 22:35:45
"""
import arcpy
from sys import argv

def prueba(_1985_tif="C:\\Users\\Joaco\\Proyecto pampa\\Tablas de cobertura\\Raster 85_21\\1985.tif", ine_depto="ine_depto", Field_Name_Existing_or_New_="bc_anio", Expression="1985", Uru_1985_csv="C:\\Users\\Joaco\\Proyecto pampa\\Tablas de cobertura\\Con modelo\\Uru_1985.csv"):  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Raster to Polygon (Raster to Polygon) 
    Uru_1985 = "C:\\Users\\Joaco\\Proyecto pampa\\Intento\\Intento.gdb\\Uru_1985"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.RasterToPolygon_conversion(in_raster=_1985_tif, out_polygon_features=Uru_1985, simplify="SIMPLIFY", raster_field="Value", create_multipart_features="SINGLE_OUTER_PART", max_vertices_per_feature=None)

    # Process: Project (Project) 
    Uru_1985_Project = "C:\\Users\\Joaco\\Proyecto pampa\\Intento\\Intento.gdb\\Uru_1985_Project"
    arcpy.Project_management(in_dataset=Uru_1985, out_dataset=Uru_1985_Project, out_coor_system="PROJCS['WGS_1984_UTM_Zone_21S',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',10000000.0],PARAMETER['Central_Meridian',-57.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", transform_method=[], in_coor_system="GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

    # Process: Intersect (Intersect) 
    Uru_1985_Project_Intersect = "C:\\Users\\Joaco\\Proyecto pampa\\Intento\\Intento.gdb\\Uru_1985_Project_Intersect"
    arcpy.Intersect_analysis(in_features=[[Uru_1985_Project, ""], [ine_depto, ""]], out_feature_class=Uru_1985_Project_Intersect, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

    # Process: Add Field (Add Field) 
    Uru_1985_Project_Intersect_2_ = arcpy.AddField_management(in_table=Uru_1985_Project_Intersect, field_name="bc_anio", field_type="DOUBLE", field_precision=None, field_scale=None, field_length=None, field_alias="bc_anio", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) 
    Uru_1985_Project_Intersect_3_ = arcpy.CalculateField_management(in_table=Uru_1985_Project_Intersect_2_, field=Field_Name_Existing_or_New_, expression=Expression, expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

    # Process: Copy Rows (Copy Rows) 
    arcpy.CopyRows_management(in_rows=Uru_1985_Project_Intersect_3_, out_table=Uru_1985_csv, config_keyword="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Joaco\Proyecto pampa\Intento\Intento.gdb", workspace=r"C:\Users\Joaco\Proyecto pampa\Intento\Intento.gdb"):
        prueba(*argv[1:])
